version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_TESLALL_1126Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/vijetadixit
  gitUsername: Karthik-V-IBM-10
  gitBranch: Test
services:
- serviceName: project.siqa_teslall_1126.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsertNew
  packages:
  - name: SIQA_TESLALL_1126Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_teslall_1126.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_TESLALL_1126Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_teslall_1126.integrations:tesstdaf
  packages:
  - name: SIQA_TESLALL_1126Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
